name: lklk
description: "lklk"
publish_to: none
version: 2.2.58+58
#//vvvv1234    svga
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_staggered_animations: ^1.1.1
  country_flags: ^3.2.0
  font_awesome_flutter: ^10.6.0
  dynamic_tabbar: ^1.0.5
  google_sign_in: ^6.2.1
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  http: ^1.3.0
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.1
  pin_code_fields: ^8.0.1
  avatar_glow: ^3.0.1
  image_picker: ^1.0.7
  progress_state_button: ^1.0.4
  chewie: ^1.8.1
  dio: ^5.4.3+1
  oktoast: ^3.4.0
  photo_view: ^0.15.0
  just_audio: ^0.9.37
  stop_watch_timer: ^3.1.1
  record: ^6.0.0
  provider: ^6.1.2
  emoji_picker_flutter: ^4.3.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  url_launcher: ^6.2.6
  equatable: ^2.0.5
  shimmer_container: ^0.0.2
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  zego_express_engine: ^3.12.5
  permission_handler: ^11.3.0
  encrypt: ^5.0.3
  zego_zim: ^2.21.1+1
  faker: ^2.1.0
  transparent_image: ^2.0.1
  flutter_svga: ^0.0.6
  flutter_cache_manager: ^3.3.1
  path_provider: ^2.1.2
  popup_menu: ^2.0.0
  wave_blob: ^1.0.5
  universal_io: ^2.2.2
  animated_emoji: ^3.1.0
  infinite_scroll_pagination: ^5.0.0
  flutter_image_slideshow: ^0.1.6
  path: ^1.9.0
  text_scroll: ^0.2.0
  focused_menu_custom: ^1.2.0
  x_overlay: ^1.0.0
  flutter_animate: ^4.5.2
  crop_your_image: ^1.0.4
  # lklk_game_add
  webview_flutter: ^4.4.2
  # webview_flutter_android: 4.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^8.0.2
  flutter_downloader: ^1.11.8
  flutter_image_compress: ^2.3.0
  image: ^4.3.0
  skeletonizer: ^2.1.0+1
  flutter_background: ^1.2.0
  flutter_email_sender: ^7.0.0
  flutter_form_builder: ^9.6.0
  google_mobile_ads: ^5.3.1
  dropdown_search: ^6.0.2
  file_picker: ^10.1.2
  marquee: ^2.3.0
  flutter_foreground_task: ^8.17.0
  flutter_local_notifications: ^18.0.1
  wakelock_plus: ^1.2.10
  logger: ^2.5.0
  image_cropper: ^9.1.0
  animated_to: ^0.3.2
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  crypto: ^3.0.3
  appwrite: ^20.3.2
  flutter_dotenv: ^5.1.0
  background_downloader: 9.2.6
  get_ip_address: ^0.0.7
  data_table_2: ^2.6.0
  # uuid: ^4.5.1
  persistent_device_id: ^1.1.0
  pull_to_refresh_new: ^2.0.5
  in_app_purchase: ^3.1.13
  on_audio_query: ^2.9.0
  web_socket_channel: ^3.0.3
  vm_service: ^14.2.4
  livekit_client: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_gen: ^5.9.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo_lklk_color.jpg
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
dependency_overrides:
  intl: ^0.17.0
  flutter_web_auth_2: ^4.1.0
  webview_flutter_android:
    path: packages/webview_flutter_android
  on_audio_query_android:
    path: packages/on_audio_query_android
flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
    rive: true
    lottie: true
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/frames_Gif/
    - assets/icons/
    - assets/icons/user_vip_sheet_icons/
    - assets/icons/rooms_icons/
    - assets/images/
    - assets/level_image/
    - assets/top_bar_room/
    - assets/top_frames/
    - assets/vip_entry_name/
    - assets/vip_frames/
    - assets/vip_levels/
    - assets/vip_pages/
    - assets/vip_sheilds/
    - assets/waves/
    - assets/smiles/
    - assets/vip_chat_body/
    - assets/vip_chat_body/vip1/
    - assets/vip_chat_body/vip2/
    - assets/vip_chat_body/vip3/
    - assets/vip_chat_body/vip4/
    - assets/vip_chat_body/vip5/
    - assets/images/dice/
    - assets/images/PSR/
    - assets/lucky_bag/dialog_send_lucky_bag/
    - assets/lucky_bag/result_lucky_bag/
    - assets/lucky_bag/
    # - assets/sounds/
    - assets/images/player/
    - assets/tasks/images/
    - assets/tasks/svg/
    - assets/socail_media_svg/
    - assets/invitation_page/
    - assets/badges/
    - assets/badges/diamond_badges/
    - assets/badges/stars_badges/
    - assets/images/my_profile_icon/
    - assets/icons/home_nav_bar_icon/
    - assets/images/my_profile_icon/relation_bar/
    - assets/badges/user_badges/
    - assets/icons/room_btn/
    - assets/icons/room_settings/
    - assets/images/rooms/rooms_frames/
    - assets/images/splash/
    - assets/icons/settings_icons/
    - assets/event/
    - assets/wakala_chanllage/
    - assets/cp_chanllage/
    # - svga_files/   
    - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
flutter_intl:
  enabled: true
  arb-dir: lib/l10n
  template-arb-file: intl_en.arb
  output-dir: lib/l10n/generated
  localizely:
    project_id: com.bwmatbw.lklklivechatapp
